[package]
name = "logs-narrator"
version = "0.2.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Merge logs to tell a story"
edition = "2021"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
chrono = "0.4.26"
colored = "2.0.4"
regex = "1.9.0"
