[package]
name = "logs-narrator"
version = "0.4.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Merge logs to tell a story"
repository = "https://github.com/agourlay/logs-narrator"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["logs", "merger"]
edition = "2024"

[dependencies]
clap = { version = "4.5.66", features = ["derive"] }
chrono = "0.4.45"
colored = "3.1.1"
regex = "1.13.1"

[profile.release]
lto = "fat"
codegen-units = 1