[package]
name = "logs-narrator"
version = "0.2.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Merge logs to tell a story"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
chrono = "0.4.34"
colored = "2.1.0"
regex = "1.10.3"
